# Generated by Django 5.0 on 2023-12-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('semestreAno', models.CharField(max_length=55)),
            ],
        ),
    ]
